use policia;

INSERT INTO `profissao` (`id_profissao`,`nome_profissao`) VALUES 
 (1,'Nenhuma'),
 (2,'Arquitecto'),
 (3,'Desenhador'),
 (4,'Engenheiro'),
 (5,'Técnico'),
 (6,'Geólogo'),
 (7,'Artistas de teatro, bailado, cinema, r�dio e televis�o'),
 (8,'Artista de circo'),
 (9,'Escultor'),
 (10,'Músico'),
 (11,'Pintor'),
 (12,'Cantor'),
 (13,'Toureiros'),
 (14,'Auditor'),
 (15,'Consultor fiscal'),
 (16,'Contabilista'),
 (17,'Economista'),
 (18,'Técnico oficial de contas'),
 (19,'Enfermeiro'),
 (20,'Fisioterapeuta'),
 (21,'Nutricionista'),
 (22,'Parteira'),
 (23,'Advogado'),
 (24,'Dentista'),
 (25,'Médico analista'),
 (26,'Médico cirurgiao'),
 (27,'Médico de clínica geral'),
 (28,'Dentista'),
 (29,'Médico estomatologista'),
 (30,'Médico fisiatra'),
 (31,'Médico gastroenterologista'),
 (32,'Médico oftalmologista'),
 (33,'Médico ortopedista'),
 (34,'Médico otorrinolaringologista'),
 (35,'Médico pediatra'),
 (36,'Médico radiologista'),
 (37,'Professor'),
 (38,'Revisor de contas'),
 (39,'Notário'),
 (40,'Psicólogo'),
 (41,'Sociólogo'),
 (42,'Sacerdote'),
 (43,'Pastor'),
 (44,'Imam'),
 (45,'Ama'),
 (46,'Analista de sistemas'),
 (47,'Arqueólogo'),
 (48,'Assistente social'),
 (49,'Astrólogo'),
 (50,'Biólogo'),
 (51,'Consultor'),
 (52,'Desportista'),
 (53,'Esteticista, manicur e pedicur'),
 (54,'Guia-intérprete'),
 (55,'Jornalista/repórter'),
 (56,'Repórter fotográfo'),
 (57,'Massagista'),
 (58,'Mediador imobiliário'),
 (59,'Programador informático'),
 (60,'Publicitário'),
 (61,'Tradutor'),
 (62,'Farmacéutico'),
 (63,'Designer'),
 (64,'Veterinário');
